ERROR:root:Error in bot.
Traceback (most recent call last):
  File "opponent_bots/easy_bot.py", line 40, in <module>
    do_turn(planet_wars)
  File "opponent_bots/easy_bot.py", line 18, in do_turn
    strongest_planet = max(state.my_planets(), key=lambda p: p.num_ships, default=None)
TypeError: max() got an unexpected keyword argument
